site_name: Ristorante da Michele
site_description: Das Ristorante da Michele bietet eine täglich wechselnde Karte mit frischen Fisch- und Fleischgerichten sowie den üblichen italienischen Klassikern.
site_author: Vincenzo Romano
site_url: 'https://da-michele.com'

# repo_name: da-michele/da-michele.com
# repo_url: 'https://github.com/da-michele/da-michele.com'
# edit_uri: blob/master/docs/src/markdown

copyright: |
  Copyright &copy; 2022 <a href="//da-michele.com" target="_blank" rel="noopener">Ristorante da Michele</a>

docs_dir: docs/src

theme:
  name: material
  custom_dir: docs/theme
  language: de
  font: false
  favicon: assets/images/favicon.png
  logo: assets/images/logo.webp
  icon:
    # logo: fontawesome/solid/pizza-slice
    # repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Wechsle in den dunklen Modus
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Wechsle in den hellen Modus
  features:
    - announce.dismiss
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

nav:
  - Startseite: 'index.md'
  - Menü: 'menu.md'
  - Impressum: 'imprint.md'
  - Restaurant:
      - Über: 'restaurant/about.md'
      - Karriere: 'restaurant/career.md'
      - Gutschein: 'restaurant/voucher.md'
  - Legal:
      - Datenschutz: 'legal/privacy.md'
      - Bedingungen: 'legal/terms.md'

extra:
  generator: false
  # homepage: https://da-michele.com
  social:
    - name: Facebook
      icon: fontawesome/brands/facebook
      link: '//www.facebook.com/pages/category/Italian-Restaurant/Pizzeria-Da-Michele-2293017134358842/'
    # - name: GitHub
    #   icon: fontawesome/brands/github
    #   link: //github.com/da-michele
    - name: Instagram
      icon: fontawesome/brands/instagram
      link: '//instagram.com/da_michele_badenbaden'
    - name: Apple Maps
      icon: maps_apple
      link: '//maps.apple.com/?ll=48.786975,8.1936724&address=Ristorante+da+Michele,Sinzheimer+Strasse+4,Baden-Baden,Germany&z=19&dirflg=d'
    - name: Google Maps
      icon: maps_google
      link: '//www.google.com/maps/dir/?api=1&origin=&destination=Ristorante+Da+Michele%2C+Sinzheimer+Str.+4%2C+76532+Baden-Baden%2C+Germany&travelmode=driving&dir_action=navigate&center=48.786975,8.1936724&zoom=19&basemap=roadmap&layer=traffic'
    - name: HERE Maps
      icon: maps_here
      link: '//wego.here.com/directions/drive//Ristorante-da-Michele,-Sinzheimer-Straße-4,-76532-Baden-Baden?map=48.78701,8.19363,15,traffic'
    - name: Waze
      icon: maps_waze
      link: '//www.waze.com/ul?q=Ristorante%20Da%20Michele&ll=48.786975,8.1936724&navigate=yes'

extra_css:
  - css/extra.css

markdown_extensions:
  # - abbr
  - admonition
  - attr_list
  # - def_list
  # - footnotes
  - md_in_html
  - meta
  # - smarty:
  #     smart_quotes: false
  # - tables
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ''
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: da-michele
      repo: da-michele.com
  # - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  # - pymdownx.progressbar
  # - pymdownx.striphtml
  # - pymdownx.snippets:
  #     base_path: 'includes'
  #     check_paths: true
  # - pymdownx.keys:
  #     separator: '\uff0b'
  - pymdownx.details
  # - pymdownx.saneheaders
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: de
